name: Install python dependencies
description: Install python dependencies with pip, with caching
runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: pyproject.toml
