name: Lint frontend

on:
  pull_request:
    types:
      - 'ready_for_review'
      - 'opened'
      - 'synchronize'
  push:
    branches:
      - 'main'
  merge_group:
  workflow_dispatch:

defaults:
  run:
    working-directory: invokeai/frontend/web

jobs:
  lint-frontend:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: 'pnpm install --prefer-frozen-lockfile'
      - name: Typescript
        run: 'pnpm run lint:tsc'
      - name: Madge
        run: 'pnpm run lint:madge'
      - name: ESLint
        run: 'pnpm run lint:eslint'
      - name: Prettier
        run: 'pnpm run lint:prettier'
